// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Off-box backup freshness, derived from the `.backup-last-ok` marker.
 */
export type BackupStatus = { 
/**
 * Unix epoch (seconds) of the last confirmed-fresh backup check, or
 * `null` when no marker exists yet (Layer 1 unarmed / never succeeded).
 */
last_ok_epoch: bigint | null, 
/**
 * Age of that confirmation in seconds, or `null` when unknown.
 */
age_seconds: bigint | null, 
/**
 * True only when a marker exists AND is older than the threshold.
 */
stale: boolean, 
/**
 * The staleness threshold in seconds, for display.
 */
stale_threshold_seconds: bigint, };
