// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ingest batch, with the count of cards it brought in.
 */
export type Batch = { id: number, batch_type: string, name: string | null, notes: string | null, order_id: number | null, binder_id: number | null, created_at: string, card_count: number, };
