// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Batch } from "./Batch";
import type { CollectionRow } from "./CollectionRow";

/**
 * A batch plus the cards it brought in.
 */
export type BatchDetail = { batch: Batch, cards: Array<CollectionRow>, };
