// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable binder fields. A `None` field is left unchanged.
 */
export type BinderEdit = { name: string | null, description: string | null, color: string | null, binder_type: string | null, pocket_size: number | null, storage_location: string | null, };
