// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotPrinting } from "./SlotPrinting";

/**
 * One binder slot — a single card number and all its printings.
 */
export type BinderSlot = { card_id: string, number: string, name: string, rarity: string | null, image_large: string | null, 
/**
 * `base` | `secret` | `subset` | `promo`.
 */
section: string, printings: Array<SlotPrinting>, };
