// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSet } from "./ExternalSet";
import type { SlotPrinting } from "./SlotPrinting";

/**
 * One binder slot — a single card number and all its printings.
 */
export type BinderSlot = { card_id: string, number: string, name: string, rarity: string | null, image_large: string | null, 
/**
 * `base` | `secret` | `subset` | `promo`. Bundles use `base` for
 * every slot since they have no rarity-tier sections.
 */
section: string, printings: Array<SlotPrinting>, 
/**
 * Home set of the slot's card when different from the container —
 * bundle slots use this to surface "lives in Obsidian Flames" and
 * to route the card-detail link. `None` for regular set slots.
 */
external_set: ExternalSet | null, };
