// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinderSetInfo } from "./BinderSetInfo";
import type { BinderSlot } from "./BinderSlot";

/**
 * A single rendered binder page with master-set progress.
 */
export type BinderPage = { set: BinderSetInfo, layout: number, page: number, total_pages: number, 
/**
 * Numbered-set card count, and how many of those the user owns.
 */
base_total: number, base_owned: number, 
/**
 * Printing count across every visible section, and how many are owned.
 */
master_total: number, master_owned: number, slots: Array<BinderSlot>, };
