// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Binder } from "./Binder";
import type { CollectionRow } from "./CollectionRow";

/**
 * A binder plus the cards assigned to it.
 */
export type BinderDetail = { binder: Binder, cards: Array<CollectionRow>, };
