// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A binder, with the count of cards assigned to it.
 */
export type Binder = { id: number, name: string, description: string | null, color: string | null, binder_type: string | null, pocket_size: number, storage_location: string | null, created_at: string, updated_at: string, card_count: number, };
