// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Header shown above a binder. Renders both real sets (kind="set") and
 * logical-set containers like Trick or Trade bundles (kind="bundle").
 * For bundles, `series` is the synthetic label ("Trick or Trade Bundle")
 * and total/printed_total are `None` so the base-completion bar hides.
 */
export type BinderSetInfo = { set_code: string, name: string, series: string, total: number | null, printed_total: number | null, 
/**
 * `"set"` for real sets, `"bundle"` for TTBB-style containers.
 */
kind: string, };
