// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Set header shown above a binder.
 */
export type BinderSetInfo = { set_code: string, name: string, series: string, total: number | null, printed_total: number | null, };
