// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bundle } from "./Bundle";
import type { BundleSlot } from "./BundleSlot";

export type BundleDetail = { bundle: Bundle, slots: Array<BundleSlot>, };
