// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bundle's summary header, used for the index list.
 */
export type Bundle = { slug: string, name: string, year: number, group_id: number, 
/**
 * Total products in the bundle (typically 30 for TTBB).
 */
slot_count: number, 
/**
 * Number of products the user owns at least one copy of (via any
 * printing tied to a product in the bundle's group).
 */
owned_count: number, };
