// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One product in a bundle, resolved to the parent card's printing
 * when the cross-group bridge linked them. When resolution fails the
 * product fields are still present but `printing_id` is `None` — the
 * UI shows the slot as "needs ingest fix" instead of letting the user
 * add the wrong thing.
 */
export type BundleSlot = { product_id: number, product_name: string, collector_number: string, image_url: string | null, 
/**
 * Sortable numeric prefix of `collector_number` — driver of slot
 * order in the grid.
 */
number_sortable: number, printing_id: string | null, card_id: string | null, card_name: string | null, set_code: string | null, set_name: string | null, number: string | null, variant: string | null, owned_count: number, };
