// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `(set_code, number)` pair — the modal's evolution link uses this to
 * resolve a card name to a specific printing.
 */
export type CardRef = { set_code: string, number: string, };
