// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-card copy count for the stats-page histogram. One row per
 * catalogued card in the set, in collector-number order; `copies` is
 * the total physical count across every variant.
 */
export type CardCopyCount = { number: string, number_sortable: number, rarity: string | null, copies: number, };
