// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-card copy count for the stats-page histogram. One row per
 * catalogued card in the set, in collector-number order; `copies` is
 * the total physical count across every variant.
 */
export type CardCopyCount = { number: string, number_sortable: number, 
/**
 * Canonical spelling from the `rarities` table where the tier is
 * known, else the raw catalog string.
 */
rarity: string | null, 
/**
 * Group alias for the tier — the histogram paints its columns by it.
 */
rarity_grp: string | null, copies: number, };
