// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { CollectionEntry } from "./CollectionEntry";
import type { PrintingInfo } from "./PrintingInfo";

/**
 * The full card-detail payload.
 */
export type CardDetail = { card: Card, printings: Array<PrintingInfo>, copies: Array<CollectionEntry>, };
