// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the global catalog-search results.
 *
 * Lightweight by design — the grid view just needs the image + label
 * fields, and `owned_count` so the frontend can dim unowned tiles.
 */
export type CatalogSearchRow = { card_id: string, set_code: string, set_name: string, number: string, name: string, rarity: string | null, image_small: string | null, 
/**
 * Sum of copies the user owns across every printing of this card.
 */
owned_count: number, };
