// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved collection view.
 */
export type CollectionView = { id: number, name: string, description: string | null, filters_json: string, created_at: string, updated_at: string, };
