// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row from the `collection` table.
 */
export type CollectionEntry = { id: number, printing_id: string, condition: string, language: string, purchase_price: number | null, sale_price: number | null, acquired_at: string, source: string, notes: string | null, tags: string | null, graded: boolean, grade_company: string | null, grade_value: number | null, grade_cert: string | null, status: string, order_id: number | null, binder_id: number | null, deck_id: number | null, batch_id: number | null, };
