// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A collection entry joined to its printing and card — the display-ready
 * shape the `/collection` UI renders.
 */
export type CollectionRow = { id: number, printing_id: string, condition: string, language: string, purchase_price: number | null, sale_price: number | null, acquired_at: string, source: string, notes: string | null, status: string, graded: boolean, binder_id: number | null, deck_id: number | null, variant: string, card_id: string, set_code: string, number: string, name: string, rarity: string | null, image_small: string | null, };
