// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A collection entry joined to its printing and card — the display-ready
 * shape the `/collection` UI renders.
 */
export type CollectionRow = { id: number, printing_id: string, condition: string, language: string, purchase_price: number | null, sale_price: number | null, acquired_at: string, source: string, notes: string | null, status: string, graded: boolean, binder_id: number | null, deck_id: number | null, variant: string, card_id: string, set_code: string, 
/**
 * Full human-readable set name (e.g. "Surging Sparks", "Base Set") —
 * preferred over `set_code` for any column or breadcrumb label.
 */
set_name: string, 
/**
 * The collector-facing 3-letter set code (e.g. "MEW", "PFL"), if known.
 */
set_ptcgo_code: string | null, set_symbol_url: string | null, number: string, name: string, rarity: string | null, 
/**
 * Artist credit, surfaced so the /collection search can filter by it.
 */
artist: string | null, 
/**
 * `Pokémon` | `Trainer` | `Energy`.
 */
supertype: string | null, 
/**
 * JSON array, e.g. `["Supporter"]` or `["Basic","ex"]`.
 */
subtypes: string | null, 
/**
 * JSON array of the card's energy types, e.g. `["Fire"]`.
 */
types: string | null, 
/**
 * JSON array of attacks, each with a `cost` energy list — the table
 * renders one pip line per attack.
 */
attacks: string | null, 
/**
 * Latest TCGplayer market price for this exact printing (NULL when
 * the printing isn't linked to a product, or no snapshot exists).
 */
market_price: number | null, image_small: string | null, 
/**
 * Free-text description carried by user_printings rows (the
 * "Missing Variant" escape hatch). NULL for catalog printings.
 */
variant_description: string | null, };
