// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitResult } from "./CommitResult";
import type { SealedCommitResult } from "./SealedCommitResult";

/**
 * The outcome of committing a combined import.
 */
export type CombinedCommitResult = { singles: CommitResult, sealed: SealedCommitResult, skipped: number, };
