// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolutionReport } from "./ResolutionReport";
import type { SealedResolutionReport } from "./SealedResolutionReport";
import type { SkippedRow } from "./SkippedRow";

/**
 * The preview of a combined import: the single and sealed resolutions kept
 * strictly apart (the garden wall), plus rows dropped as out of scope.
 */
export type CombinedReport = { singles: ResolutionReport, sealed: SealedResolutionReport, skipped: Array<SkippedRow>, };
