// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of committing an import.
 */
export type CommitResult = { batch_id: number, added: number, skipped: number, };
