// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the `conditions` table. Mirrors the schema 1:1.
 */
export type Condition = { name: string, multiplier: number, rank: number, };
