// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-copy summary nested under a [`SearchRow`] in the expand/drill-down.
 */
export type CopySummary = { id: number, condition: string, language: string, status: string, graded: boolean, purchase_price: number | null, acquired_at: string, binder_id: number | null, deck_id: number | null, };
