// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable per-copy fields. A `None` field is left unchanged.
 */
export type CopyEdit = { condition: string | null, language: string | null, purchase_price: number | null, sale_price: number | null, notes: string | null, tags: string | null, graded: boolean | null, grade_company: string | null, grade_value: number | null, grade_cert: string | null, };
