// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionRow } from "./CollectionRow";
import type { UserPrinting } from "./UserPrinting";

export type CreateMissingVariantResult = { user_printing: UserPrinting, copies: Array<CollectionRow>, };
