// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMissingVariant = { card_id: string, description: string | null, 
/**
 * Number of physical copies to add to the collection in this submit.
 * 0 is allowed — creates the variant slot only.
 */
qty: number, 
/**
 * Optional first manual-price entry. Recorded once if `price` is set.
 */
price: number | null, observed_at: string | null, note: string | null, };
