// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionRow } from "./CollectionRow";
import type { Deck } from "./Deck";

/**
 * A deck plus the cards assigned to it.
 */
export type DeckDetail = { deck: Deck, cards: Array<CollectionRow>, };
