// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A deck, with the count of cards assigned to it.
 */
export type Deck = { id: number, name: string, description: string | null, format: string | null, owner: string | null, 
/**
 * `idea` | `ready` | `built`.
 */
state: string, sleeve_color: string | null, storage_location: string | null, notes: string | null, created_at: string, updated_at: string, card_count: number, };
