// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable deck fields. A `None` field is left unchanged.
 */
export type DeckEdit = { name: string | null, description: string | null, format: string | null, owner: string | null, state: string | null, sleeve_color: string | null, storage_location: string | null, notes: string | null, };
