// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pointer to the home set of a slot's underlying card, when that set
 * differs from the container being rendered. Populated only for bundle
 * slots (TTBB products are reprints of cards in other sets) — `None`
 * for normal set slots.
 */
export type ExternalSet = { set_code: string, name: string, };
