// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `is:` flag value, for autocomplete.
 */
export type FlagInfo = { flag: string, help: string | null, };
