// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One keyword, for autocomplete + the help page.
 */
export type KeywordInfo = { canonical: string, aliases: Array<string>, operators: Array<string>, kind: string, help: string | null, };
