// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One manual price observation for a printing.
 */
export type ManualPrice = { id: number, printing_id: string, price: number, observed_at: string, note: string | null, created_at: string, };
