// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingCard } from "./MissingCard";

/**
 * The set of cards a user is missing, ready for a TCGplayer Mass Entry
 * paste. Built by [`missing_for_export`]; the front-end filters by scope
 * (base vs master) and per-card secret-rare confirmation before assembling
 * the final paste text.
 */
export type MissingExport = { set_code: string, set_name: string, 
/**
 * The set code used in the Mass Entry lines: TCGplayer's own
 * `group.abbreviation` when known, else the PTCGO code. `None` means the
 * set has no usable code, so every line is unmappable (the UI warns).
 */
ptcgo_code: string | null, cards: Array<MissingCard>, };
