// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One card the user owns no copy of, with its ready-to-paste Mass Entry
 * line (or `None` when the set lacks a `ptcgo_code` to anchor it).
 */
export type MissingCard = { card_id: string, number: string, name: string, 
/**
 * `base` | `secret` | `subset` | `promo`.
 */
section: string, 
/**
 * `"1 <Name> - <###/###> [<CODE>]"` (or `"1 <Name> [<CODE>]"` when the
 * card has no TCGplayer collector number), or `None` when unmappable
 * (the set has no code).
 */
mass_entry_line: string | null, };
