// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields for creating a batch.
 */
export type NewBatch = { batch_type: string, name: string | null, notes: string | null, order_id: number | null, binder_id: number | null, };
