// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields for creating a binder.
 */
export type NewBinder = { name: string, description: string | null, color: string | null, binder_type: string | null, pocket_size: number | null, storage_location: string | null, };
