// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields supplied when adding a copy to the collection. Optional fields
 * fall back to schema defaults.
 */
export type NewCopy = { printing_id: string, condition: string | null, language: string | null, purchase_price: number | null, acquired_at: string | null, source: string, status: string | null, notes: string | null, order_id: number | null, binder_id: number | null, deck_id: number | null, batch_id: number | null, };
