// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input fields for creating a manual price.
 */
export type NewManualPrice = { printing_id: string, price: number, 
/**
 * ISO-8601 timestamp. `None` → defaults to now (UTC).
 */
observed_at: string | null, note: string | null, };
