// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields for adding a sealed product to the collection.
 */
export type NewSealed = { product_id: number, quantity: number | null, condition: string | null, purchase_price: number | null, purchase_date: string | null, source: string | null, seller_name: string | null, notes: string | null, };
