// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input fields for creating a user_printing.
 */
export type NewUserPrinting = { card_id: string, 
/**
 * Free-text description of the off-catalog variant. Optional.
 */
description: string | null, };
