// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields for saving a new view.
 */
export type NewView = { name: string, description: string | null, filters_json: string, };
