// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields for adding a wish.
 */
export type NewWish = { card_id: string, printing_id: string | null, max_price: number | null, priority: number | null, notes: string | null, };
