// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionRow } from "./CollectionRow";
import type { Order } from "./Order";

/**
 * An order plus the copies it brought in.
 */
export type OrderDetail = { order: Order, cards: Array<CollectionRow>, };
