// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A purchase order with the count of cards it brought in.
 */
export type Order = { id: number, order_number: string | null, source: string, seller_name: string | null, order_date: string | null, subtotal: number | null, shipping: number | null, tax: number | null, total: number | null, shipping_status: string | null, estimated_delivery: string | null, notes: string | null, created_at: string, card_count: number, };
