// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of an order — a printing, a quantity, and the per-card price.
 */
export type OrderLine = { printing_id: string, quantity: number, purchase_price: number | null, };
