// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricePoint } from "./PricePoint";

/**
 * Full price history for one printing × price_type. The frontend renders
 * one chart line per series. v1 only emits `price_type = "market"`.
 */
export type PriceSeries = { printing_id: string, variant: string, 
/**
 * TCGplayer sub_type — `Normal` / `Holofoil` / `Reverse Holofoil` / …
 */
sub_type_name: string, price_type: string, points: Array<PricePoint>, };
