// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One snapshot in a printing's market-price history.
 */
export type PricePoint = { 
/**
 * `YYYY-MM-DD` — the day TCGCSV was queried (see `import_prices`).
 */
date: string, price: number, };
