// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One printing of a card, with how many copies the user owns and the
 * latest TCGplayer market price (NULL until printing↔product linking lands).
 */
export type PrintingInfo = { printing_id: string, variant: string, language: string, badge_overlay: string | null, image_override: string | null, deprecated: boolean, owned_count: number, market_price: number | null, 
/**
 * TCGplayer product id, used to deep-link a printing to its product page.
 */
tcgplayer_product_id: number | null, 
/**
 * True when this row is a user_printings entry — the "Missing
 * Variant" escape hatch. Renders with an italic + (user) tag in
 * the UI.
 */
is_user_added: boolean, 
/**
 * Free-text variant description carried by user_printings rows.
 */
description: string | null, };
