// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rarity tier within a set, with how many of its cards the user owns.
 */
export type RarityCount = { rarity: string, total_cards: number, owned_cards: number, };
