// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedRow } from "./ResolvedRow";
import type { UnmatchedRow } from "./UnmatchedRow";

/**
 * The outcome of resolving an import file — a preview shown before commit.
 */
export type ResolutionReport = { matched: Array<ResolvedRow>, unmatched: Array<UnmatchedRow>, };
