// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sealed row that resolved cleanly to a catalog product — ready to commit.
 */
export type ResolvedSealedRow = { source_line: number, product_id: number, name: string, category: string, set_code: string | null, quantity: number, condition: string, purchase_price: number | null, purchase_date: string | null, notes: string | null, };
