// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sealed-collection row joined to its catalog product.
 */
export type SealedEntry = { id: number, product_id: number, quantity: number, condition: string | null, purchase_price: number | null, sale_price: number | null, purchase_date: string | null, source: string | null, seller_name: string | null, notes: string | null, status: string, added_at: string, name: string, category: string, set_code: string | null, image_url: string | null, };
