// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sealed product from the catalog — used when searching for something to
 * add to the collection.
 */
export type SealedProduct = { product_id: number, set_code: string | null, name: string, category: string, image_url: string | null, release_date: string | null, };
