// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable sealed-entry fields, including `status` for disposal. A `None`
 * field is left unchanged.
 */
export type SealedEdit = { quantity: number | null, condition: string | null, purchase_price: number | null, sale_price: number | null, purchase_date: string | null, source: string | null, seller_name: string | null, notes: string | null, status: string | null, };
