// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedSealedRow } from "./ResolvedSealedRow";
import type { UnmatchedSealedRow } from "./UnmatchedSealedRow";

/**
 * The outcome of resolving the sealed rows of an import file — the sealed
 * half of the preview shown before commit.
 */
export type SealedResolutionReport = { matched: Array<ResolvedSealedRow>, unmatched: Array<UnmatchedSealedRow>, };
