// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of committing the sealed half of an import.
 */
export type SealedCommitResult = { added: number, skipped: number, };
