// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchRow } from "./SearchRow";

/**
 * One page of search results plus the size of the whole result set.
 */
export type SearchPage = { rows: Array<SearchRow>, 
/**
 * Rows the query matches in total, ignoring `limit`/`offset`.
 */
total: number, limit: number, offset: number, };
