// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopySummary } from "./CopySummary";

/**
 * One search result row — a single printing, owned or not (decision D3).
 */
export type SearchRow = { printing_id: string, card_id: string, set_code: string, set_name: string, set_ptcgo_code: string | null, set_symbol_url: string | null, number: string, name: string, rarity: string | null, artist: string | null, supertype: string | null, subtypes: string | null, types: string | null, attacks: string | null, market_price: number | null, image_small: string | null, variant: string, variant_description: string | null, 
/**
 * True when at least one copy is owned (`owned_count > 0`).
 */
owned: boolean, owned_count: number, 
/**
 * The owned copies of this printing (empty when unowned).
 */
copies: Array<CopySummary>, };
