// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagInfo } from "./FlagInfo";
import type { KeywordInfo } from "./KeywordInfo";

/**
 * The data-driven search vocabulary served to the frontend.
 */
export type SearchVocabulary = { keywords: Array<KeywordInfo>, flags: Array<FlagInfo>, };
