// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RarityCount } from "./RarityCount";

/**
 * Analytical breakdown of a single set: completion against both the
 * numbered set and the master (every printing) set, the rarity split,
 * and value — the full set's market value and the value owned.
 */
export type SetAnalytics = { set_code: string, name: string, series: string, 
/**
 * Numbered cards in the set, and how many the user owns.
 */
total_cards: number, owned_cards: number, 
/**
 * Non-deprecated printings (the master set), and how many are owned.
 */
total_printings: number, owned_printings: number, 
/**
 * Market value of one of every printing, and of the copies owned.
 */
market_value: number, owned_value: number, rarities: Array<RarityCount>, };
