// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardCopyCount } from "./CardCopyCount";
import type { RarityCount } from "./RarityCount";

/**
 * Analytical breakdown of a single set: completion against both the
 * numbered set and the master (every printing) set, the rarity split,
 * and value — the full set's market value and the value owned.
 */
export type SetAnalytics = { set_code: string, name: string, series: string, 
/**
 * Base-set cards only (number ≤ printed_total — excludes secret
 * rares, subset sections, promos), and how many the user owns
 * (any variant counts).
 */
base_total_cards: number, base_owned_cards: number, 
/**
 * Numbered cards in the set, and how many the user owns.
 */
total_cards: number, owned_cards: number, 
/**
 * Non-deprecated printings (the master set), and how many are owned.
 */
total_printings: number, owned_printings: number, 
/**
 * Total physical copies of any card in the set — sums duplicates.
 */
owned_copies: number, 
/**
 * Market value: one of every printing in the set, one of every
 * printing the user owns, and the all-physical-copies sum (counts
 * duplicates).
 */
market_value: number, owned_value_unique: number, owned_value: number, rarities: Array<RarityCount>, 
/**
 * One entry per card in the set, ordered by collector number —
 * drives the stats-page copy-count histogram.
 */
copy_counts: Array<CardCopyCount>, };
