// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A set with its card count and how many of its cards the user owns —
 * the shape the `/browse` set picker renders. Bundles project into the
 * same type with `kind="bundle"` and synthesized series/null totals so
 * the picker can render them through the same tile component.
 */
export type SetSummary = { set_code: string, ptcgo_code: string | null, name: string, series: string, total: number | null, printed_total: number | null, release_date: string | null, logo_url: string | null, symbol_url: string | null, 
/**
 * Cards catalogued in the set.
 */
total_cards: number, 
/**
 * Distinct cards in the set the user owns at least one copy of.
 */
owned_cards: number, 
/**
 * Base-set cards only — `number_sortable <= printed_total`. Excludes
 * secret rares, subset sections, and promos. `None` when the set has
 * no `printed_total` so the UI can hide the bar gracefully (avoids
 * rendering 0/0 = NaN%).
 */
base_total_cards: number | null, base_owned_cards: number | null, 
/**
 * `"set"` for real catalogued sets, `"bundle"` for TTBB-style
 * logical-set containers.
 */
kind: string, };
