// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A set with its card count and how many of its cards the user owns —
 * the shape the `/browse` set picker renders.
 */
export type SetSummary = { set_code: string, ptcgo_code: string | null, name: string, series: string, total: number | null, printed_total: number | null, release_date: string | null, logo_url: string | null, symbol_url: string | null, 
/**
 * Cards catalogued in the set.
 */
total_cards: number, 
/**
 * Distinct cards in the set the user owns at least one copy of.
 */
owned_cards: number, };
