// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row skipped during a combined import (e.g. a non-Pokémon Collectr row).
 */
export type SkippedRow = { source_line: number, category: string, name: string, reason: string, };
