// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One printing within a slot.
 */
export type SlotPrinting = { printing_id: string, variant: string, deprecated: boolean, owned_count: number, market_price: number | null, };
