// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sealed row that could not be resolved, with a human-readable reason.
 */
export type UnmatchedSealedRow = { source_line: number, name: string, set_hint: string, reason: string, };
