// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row that could not be resolved, with a human-readable reason.
 */
export type UnmatchedRow = { source_line: number, set_hint: string, number: string, variant: string, reason: string, };
