// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open row of the dead-letter queue, as shown on `/ingest/unresolved`.
 */
export type UnresolvedRow = { id: number, 
/**
 * `single` | `sealed`.
 */
kind: string, 
/**
 * The import source that parked it (`csv_collectr`, `csv_manabox`, …).
 */
source: string, batch_id: number | null, source_line: number | null, set_hint: string | null, 
/**
 * Collector number (singles only).
 */
number: string | null, 
/**
 * Display hint — the card or product name as written in the import.
 */
name: string | null, 
/**
 * Variant code (singles only).
 */
variant: string | null, 
/**
 * Unit count (sealed only).
 */
quantity: number | null, 
/**
 * The resolver's human-readable reason this row didn't match.
 */
reason: string, parked_at: string, };
