// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of resolving a parked row: which side it landed on and the id
 * of the created collection / sealed row.
 */
export type UnresolvedResolveResult = { 
/**
 * `single` | `sealed`.
 */
kind: string, 
/**
 * The created `collection.id` (single) or `sealed_collection.id` (sealed).
 */
id: number, };
