// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One user-created ad-hoc printing.
 */
export type UserPrinting = { printing_id: string, card_id: string, variant: string, description: string | null, created_at: string, };
