// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValuePoint } from "./ValuePoint";

/**
 * A single value line: the whole collection, one set, or one binder.
 * FROZEN API contract (pokedumpster-e1vo.1).
 */
export type ValueSeries = { 
/**
 * `None` for the `all` dimension; otherwise the set_code or the
 * binder-id-as-string that identifies this bucket.
 */
bucket: string | null, 
/**
 * Human label — set name / binder name; `None` for `all`.
 */
label: string | null, points: Array<ValuePoint>, };
