// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point on a value series — the collection's value on a single date.
 * FROZEN API contract (pokedumpster-e1vo.1): the chart frontend (e1vo.2) is
 * built against these exact field names.
 */
export type ValuePoint = { 
/**
 * `YYYY-MM-DD`.
 */
date: string, market_value: number, cost_basis: number, card_count: number, };
