// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the variants table. Mirrors the schema 1:1.
 */
export type Variant = { code: string, label: string, short: string, rank: number, color: string, };
