// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable view fields. A `None` field is left unchanged.
 */
export type ViewEdit = { name: string | null, description: string | null, filters_json: string | null, };
