// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wishlist entry joined to its card.
 */
export type WishlistEntry = { id: number, card_id: string, 
/**
 * A specific wanted printing, or null for "any printing".
 */
printing_id: string | null, max_price: number | null, priority: number, notes: string | null, added_at: string, source: string, fulfilled_at: string | null, set_code: string, number: string, name: string, rarity: string | null, image_small: string | null, };
