// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable wish fields. A `None` field is left unchanged.
 */
export type WishEdit = { max_price: number | null, priority: number | null, notes: string | null, };
