[package]
name = "pkdump-db"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pkdump-core.workspace = true
rusqlite.workspace = true
refinery.workspace = true
thiserror.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true
csv.workspace = true

[dev-dependencies]
tempfile.workspace = true
