#!/usr/bin/env bash
# GATE spike (pd-o98z): can ONE Litestream sidecar replicate N tenant SQLite
# databases to one S3 bucket, and can any ONE of them be restored to a chosen
# point in time WITHOUT disturbing the others?
#
# Everything here is throwaway: its own podman network, its own MinIO, its own
# temp dir. It never touches prod (pkdump-prod-data, collection.sqlite, any
# pkdump-* unit) and never touches application code.
#
#   deep-dives/litestream-multi-db/run.sh          # full run + teardown
#   KEEP=1 deep-dives/litestream-multi-db/run.sh   # leave containers + WORK up
#
# Exit 0 = PASS, exit 1 = FAIL. See RESULT.md for the recorded outcome.
set -euo pipefail

LITESTREAM_IMAGE=${LITESTREAM_IMAGE:-docker.io/litestream/litestream:latest}
MINIO_IMAGE=${MINIO_IMAGE:-docker.io/minio/minio:latest}
MC_IMAGE=${MC_IMAGE:-docker.io/minio/mc:latest}

NET=lsmdb-net
MINIO_CTR=lsmdb-minio
LS_CTR=lsmdb-litestream
MINIO_PORT=${MINIO_PORT:-39900}
BUCKET=lsmdb-spike
AKID=lsmdbroot
SECRET=lsmdbsecret123

WORK=${WORK:-$(mktemp -d /tmp/lsmdb.XXXXXX)}
mkdir -p "$WORK/data" "$WORK/minio" "$WORK/restore"

# Tenants. Deliberately THREE so "restore the second one" is a real middle
# element, not just "the other one".
TENANTS=(alpha bravo charlie)

pass=0
fail=0
check() { # check <label> <expected> <actual>
	if [[ "$2" == "$3" ]]; then
		echo "  PASS  $1 (= $3)"
		pass=$((pass + 1))
	else
		echo "  FAIL  $1 (expected $2, got $3)"
		fail=$((fail + 1))
	fi
}
note() { echo "  NOTE  $*"; }

log() { printf '\n=== %s ===\n' "$*"; }

# shellcheck disable=SC2329  # invoked via trap
cleanup() {
	if [[ -n "${KEEP:-}" ]]; then
		echo
		echo "KEEP=1 — leaving containers up and WORK=$WORK in place."
		echo "  podman logs $LS_CTR"
		echo "  podman rm -f $LS_CTR $MINIO_CTR; podman network rm $NET; rm -rf $WORK"
		return
	fi
	podman rm -f "$LS_CTR" "$MINIO_CTR" >/dev/null 2>&1 || true
	podman network rm "$NET" >/dev/null 2>&1 || true
	rm -rf "$WORK"
}
trap cleanup EXIT

# sqlite helper — every tenant DB is WAL, which Litestream requires.
sq() { sqlite3 "$1" "${@:2}"; }
rows() { sqlite3 "$1" 'SELECT count(*) FROM writes;'; }

log "0. versions"
podman --version
echo -n "litestream "
podman run --rm "$LITESTREAM_IMAGE" version
sqlite3 --version

log "1. MinIO (throwaway S3) on its own network"
podman rm -f "$LS_CTR" "$MINIO_CTR" >/dev/null 2>&1 || true
podman network rm "$NET" >/dev/null 2>&1 || true
podman network create "$NET" >/dev/null
podman run -d --name "$MINIO_CTR" --network "$NET" \
	-p "127.0.0.1:$MINIO_PORT:9000" \
	-e MINIO_ROOT_USER="$AKID" -e MINIO_ROOT_PASSWORD="$SECRET" \
	-v "$WORK/minio:/data:Z" \
	"$MINIO_IMAGE" server /data >/dev/null

for _ in $(seq 60); do
	curl -fsS "http://127.0.0.1:$MINIO_PORT/minio/health/live" >/dev/null 2>&1 && break
	sleep 1
done
curl -fsS "http://127.0.0.1:$MINIO_PORT/minio/health/live" >/dev/null
echo "minio live on 127.0.0.1:$MINIO_PORT"

podman run --rm --network "$NET" \
	-e "MC_HOST_s=http://$AKID:$SECRET@$MINIO_CTR:9000" \
	"$MC_IMAGE" mb --ignore-existing "s/$BUCKET" >/dev/null
echo "bucket $BUCKET created"

log "2. ${#TENANTS[@]} tenant databases, one file each"
for t in "${TENANTS[@]}"; do
	db="$WORK/data/$t.sqlite"
	sq "$db" 'PRAGMA journal_mode=WAL;' >/dev/null
	sq "$db" 'CREATE TABLE writes (n INTEGER PRIMARY KEY, tenant TEXT, phase TEXT);'
	echo "  $db"
done

log "3. ONE config, ONE sidecar, N dbs"
# The shape under test: a `dbs:` LIST, one entry per tenant, each with its own
# replica PATH inside the SAME bucket. This mirrors what pd-fof4 would have to
# generate per tenant.
{
	echo "# generated by deep-dives/litestream-multi-db/run.sh"
	echo "snapshot:"
	echo "  interval: 24h"
	echo "  retention: 4320h"
	echo ""
	echo "dbs:"
	for t in "${TENANTS[@]}"; do
		cat <<-YAML
			  - path: /data/$t.sqlite
			    replicas:
			      - type: s3
			        bucket: $BUCKET
			        path: tenants/$t
			        region: us-east-1
			        endpoint: http://$MINIO_CTR:9000
			        force-path-style: true
			        access-key-id: $AKID
			        secret-access-key: $SECRET
		YAML
	done
} >"$WORK/litestream.yml"
cat "$WORK/litestream.yml"

# One container. One `replicate` process. All tenants.
podman run -d --name "$LS_CTR" --network "$NET" --user 0 \
	-v "$WORK/data:/data:Z" \
	-v "$WORK/litestream.yml:/etc/litestream.yml:ro,Z" \
	"$LITESTREAM_IMAGE" replicate -config /etc/litestream.yml >/dev/null

sleep 5
echo "--- databases known to the sidecar ---"
podman exec "$LS_CTR" litestream databases -config /etc/litestream.yml || true

log "4. CONCURRENT interleaved writes (phase 1)"
# Interleaved, not tenant-at-a-time: every round touches every tenant, and the
# per-tenant writers run in parallel so their transactions overlap in time.
PHASE1=25
for n in $(seq 1 $PHASE1); do
	for t in "${TENANTS[@]}"; do
		sq "$WORK/data/$t.sqlite" \
			"INSERT INTO writes (n, tenant, phase) VALUES ($n, '$t', 'p1');" &
	done
	wait
done
for t in "${TENANTS[@]}"; do
	echo "  $t: $(rows "$WORK/data/$t.sqlite") rows after phase 1"
done

# Let the sidecar flush phase 1, then take the restore marker, then leave a gap
# so the marker cannot be confused with a phase-2 write.
sleep 6
MARK=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "  restore marker: $MARK"
sleep 4

log "5. CONCURRENT interleaved writes (phase 2)"
PHASE2=25
for n in $(seq $((PHASE1 + 1)) $((PHASE1 + PHASE2))); do
	for t in "${TENANTS[@]}"; do
		sq "$WORK/data/$t.sqlite" \
			"INSERT INTO writes (n, tenant, phase) VALUES ($n, '$t', 'p2');" &
	done
	wait
done
TOTAL=$((PHASE1 + PHASE2))
for t in "${TENANTS[@]}"; do
	echo "  $t: $(rows "$WORK/data/$t.sqlite") rows after phase 2"
done

log "6. flush + stop the sidecar"
sleep 8
podman stop -t 30 "$LS_CTR" >/dev/null
podman logs "$LS_CTR" >"$WORK/litestream.log" 2>&1 || true
echo "sidecar log -> $WORK/litestream.log ($(wc -l <"$WORK/litestream.log") lines)"

log "7. objects in the bucket, per tenant"
podman run --rm --network "$NET" \
	-e "MC_HOST_s=http://$AKID:$SECRET@$MINIO_CTR:9000" \
	"$MC_IMAGE" ls -r "s/$BUCKET" | awk '{print $NF}' | sed 's#/[^/]*$##' | sort -u

# ---------------------------------------------------------------------------
# The actual assertions.
# ---------------------------------------------------------------------------
# `restore` is run in a container that can reach MinIO, with the same config;
# the DB path selects WHICH tenant's replica to read.
lsrestore() { # lsrestore <args...>
	podman run --rm --network "$NET" --user 0 \
		-v "$WORK/data:/data:Z" \
		-v "$WORK/restore:/restore:Z" \
		-v "$WORK/litestream.yml:/etc/litestream.yml:ro,Z" \
		"$LITESTREAM_IMAGE" restore -config /etc/litestream.yml "$@"
}

# The tenant under test is the SECOND one, deliberately: an off-by-one in
# config generation would sail through a tenant-#1-only test.
VICTIM=${TENANTS[1]}
OTHER_A=${TENANTS[0]}
OTHER_C=${TENANTS[2]}

log "8. point-in-time restore of tenant #2 ($VICTIM) to $MARK"
lsrestore -timestamp "$MARK" -o "/restore/$VICTIM.pit.sqlite" "/data/$VICTIM.sqlite"
check "$VICTIM restored to marker holds only phase-1 rows" \
	"$PHASE1" "$(rows "$WORK/restore/$VICTIM.pit.sqlite")"
check "$VICTIM restored to marker has no phase-2 row" \
	"0" "$(sqlite3 "$WORK/restore/$VICTIM.pit.sqlite" "SELECT count(*) FROM writes WHERE phase='p2';")"
check "$VICTIM restored to marker is the right tenant" \
	"$VICTIM" "$(sqlite3 "$WORK/restore/$VICTIM.pit.sqlite" 'SELECT DISTINCT tenant FROM writes;')"

log "9. latest restore of every tenant (independent, addressable replicas)"
for t in "${TENANTS[@]}"; do
	lsrestore -o "/restore/$t.latest.sqlite" "/data/$t.sqlite"
	check "$t latest restore is current" "$TOTAL" "$(rows "$WORK/restore/$t.latest.sqlite")"
	check "$t latest restore is the right tenant" \
		"$t" "$(sqlite3 "$WORK/restore/$t.latest.sqlite" 'SELECT DISTINCT tenant FROM writes;')"
done

log "10. IN-PLACE DR drill: roll tenant #2 back, others must not move"
before_a=$(sqlite3 "$WORK/data/$OTHER_A.sqlite" 'SELECT count(*), max(n) FROM writes;')
before_c=$(sqlite3 "$WORK/data/$OTHER_C.sqlite" 'SELECT count(*), max(n) FROM writes;')
sum_a_before=$(sha256sum "$WORK/data/$OTHER_A.sqlite" | cut -d' ' -f1)
sum_c_before=$(sha256sum "$WORK/data/$OTHER_C.sqlite" | cut -d' ' -f1)

rm -f "$WORK/data/$VICTIM.sqlite" "$WORK/data/$VICTIM.sqlite-wal" "$WORK/data/$VICTIM.sqlite-shm"
lsrestore -timestamp "$MARK" "/data/$VICTIM.sqlite"

check "$VICTIM live DB rolled back to the marker" "$PHASE1" "$(rows "$WORK/data/$VICTIM.sqlite")"
check "$OTHER_A live DB untouched (count,max)" "$before_a" \
	"$(sqlite3 "$WORK/data/$OTHER_A.sqlite" 'SELECT count(*), max(n) FROM writes;')"
check "$OTHER_C live DB untouched (count,max)" "$before_c" \
	"$(sqlite3 "$WORK/data/$OTHER_C.sqlite" 'SELECT count(*), max(n) FROM writes;')"
check "$OTHER_A file bytes unchanged" "$sum_a_before" \
	"$(sha256sum "$WORK/data/$OTHER_A.sqlite" | cut -d' ' -f1)"
check "$OTHER_C file bytes unchanged" "$sum_c_before" \
	"$(sha256sum "$WORK/data/$OTHER_C.sqlite" | cut -d' ' -f1)"

log "11. the rolled-back tenant's replica is still intact for the others"
# A restore is a READ. After rolling $VICTIM back, the untouched tenants must
# still restore to current from their own replica paths.
lsrestore -o "/restore/$OTHER_C.after.sqlite" "/data/$OTHER_C.sqlite"
check "$OTHER_C still restores to current after $VICTIM's rollback" \
	"$TOTAL" "$(rows "$WORK/restore/$OTHER_C.after.sqlite")"

# ---------------------------------------------------------------------------
# Constraint probes. Everything below is what the downstream beads (pd-fof4
# config generation, pd-fl70 provisioning, pd-v8zf DR runbook) actually have to
# build against. These are assertions too — if a future Litestream changes any
# of them, this script says so.
# ---------------------------------------------------------------------------
S3OPTS="type: s3, bucket: $BUCKET, region: us-east-1, endpoint: \"http://$MINIO_CTR:9000\", force-path-style: true, access-key-id: $AKID, secret-access-key: $SECRET"

# Run `replicate` in the foreground for a few seconds and return its log.
brief() { # brief <config-yaml> <seconds>
	printf '%s' "$1" >"$WORK/probe.yml"
	podman rm -f lsmdb-probe >/dev/null 2>&1 || true
	podman run --rm --name lsmdb-probe --network "$NET" --user 0 \
		-v "$WORK/data:/data:Z" -v "$WORK/probe.yml:/etc/litestream.yml:ro,Z" \
		"$LITESTREAM_IMAGE" replicate -config /etc/litestream.yml >"$WORK/probe.log" 2>&1 &
	sleep "$2"
	podman stop -t 10 lsmdb-probe >/dev/null 2>&1 || true
	wait 2>/dev/null || true
	cat "$WORK/probe.log"
}

log "12. CONSTRAINT: schedules are process-global, not per-database"
# The `snapshot:` block sets the level-9 (snapshot) compaction monitor. There is
# ONE monitor per process (system=store), shared by every db.
lvl9() { grep -oE 'level=9 interval=[^ ]+' <<<"$1" | head -1 | cut -d= -f3; }
top_1h=$(brief "snapshot:
  interval: 1h
  retention: 48h
dbs:
  - path: /data/$OTHER_A.sqlite
    replicas: [{$S3OPTS, path: tenants/$OTHER_A}]
" 5)
check "top-level snapshot.interval IS honoured" "1h0m0s" "$(lvl9 "$top_1h")"

per_db=$(brief "dbs:
  - path: /data/$OTHER_A.sqlite
    snapshot:
      interval: 1h
      retention: 48h
    replicas: [{$S3OPTS, path: tenants/$OTHER_A}]
" 5)
check "per-database snapshot.interval is SILENTLY IGNORED (falls back to 24h default)" \
	"24h0m0s" "$(lvl9 "$per_db")"
note "=> every tenant shares one snapshot/retention/compaction schedule."
note "=> unknown config keys do not error; a typo'd key is silently dropped."

log "13. CONSTRAINT: colliding replica paths are accepted, and LEAK ACROSS TENANTS"
# The footgun pd-fof4 has to design against: nothing validates that two dbs
# have distinct replica paths.
collide=$(brief "dbs:
  - path: /data/$OTHER_A.sqlite
    replicas: [{$S3OPTS, path: tenants/COLLIDE}]
  - path: /data/$OTHER_C.sqlite
    replicas: [{$S3OPTS, path: tenants/COLLIDE}]
" 8)
check "no error is raised for a duplicate replica path" "0" \
	"$(grep -c 'level=ERROR' <<<"$collide" || true)"
# Restore with the SAME (colliding) config that produced the replica.
podman run --rm --network "$NET" --user 0 \
	-v "$WORK/data:/data:Z" -v "$WORK/restore:/restore:Z" \
	-v "$WORK/probe.yml:/etc/litestream.yml:ro,Z" \
	"$LITESTREAM_IMAGE" restore -config /etc/litestream.yml \
	-o "/restore/collide.sqlite" "/data/$OTHER_C.sqlite"
check "restoring $OTHER_C from the collided path is byte-valid SQLite" "ok" \
	"$(sqlite3 "$WORK/restore/collide.sqlite" 'PRAGMA integrity_check;')"
note "restoring $OTHER_C from the collided path actually returns tenant: $(sqlite3 "$WORK/restore/collide.sqlite" 'SELECT DISTINCT tenant FROM writes;')"
note "=> a config-generation typo is a SILENT CROSS-TENANT DATA SUBSTITUTION."

log "14. CONSTRAINT: blast radius of a missing tenant DB is zero"
missing=$(brief "dbs:
  - path: /data/$OTHER_A.sqlite
    replicas: [{$S3OPTS, path: tenants/$OTHER_A}]
  - path: /data/absent.sqlite
    replicas: [{$S3OPTS, path: tenants/absent}]
  - path: /data/$OTHER_C.sqlite
    replicas: [{$S3OPTS, path: tenants/$OTHER_C}]
" 8)
check "a missing db does not stop the others replicating" "yes" \
	"$(grep -q "db=$OTHER_C.sqlite replica=s3" <<<"$missing" && echo yes || echo no)"
check "a missing db does not crash the process" "0" \
	"$(grep -c 'level=ERROR' <<<"$missing" || true)"

log "15. dir + pattern + watch — native N-database mode (no config generation)"
# Undocumented in the config we ship, but present in 0.5: point Litestream at a
# DIRECTORY. Replica paths are derived from the filename, so the §13 collision
# is impossible by construction, and `watch: true` picks up a tenant db created
# after the sidecar started.
mkdir -p "$WORK/data/tenants"
sqlite3 "$WORK/data/tenants/delta.sqlite" \
	"PRAGMA journal_mode=WAL; CREATE TABLE writes(n INTEGER PRIMARY KEY, tenant TEXT, phase TEXT); INSERT INTO writes VALUES(1,'delta','dir');" >/dev/null

printf '%s' "dbs:
  - dir: /data/tenants
    pattern: \"*.sqlite\"
    watch: true
    replicas: [{$S3OPTS, path: bydir}]
" >"$WORK/probe.yml"
podman rm -f lsmdb-probe >/dev/null 2>&1 || true
podman run -d --name lsmdb-probe --network "$NET" --user 0 \
	-v "$WORK/data:/data:Z" -v "$WORK/probe.yml:/etc/litestream.yml:ro,Z" \
	"$LITESTREAM_IMAGE" replicate -config /etc/litestream.yml >/dev/null
sleep 5
# A brand-new tenant appears on disk with the sidecar already running.
sqlite3 "$WORK/data/tenants/echo.sqlite" \
	"PRAGMA journal_mode=WAL; CREATE TABLE writes(n INTEGER PRIMARY KEY, tenant TEXT, phase TEXT); INSERT INTO writes VALUES(1,'echo','late');" >/dev/null
sleep 10
dirlog=$(podman logs lsmdb-probe 2>&1)
podman stop -t 10 lsmdb-probe >/dev/null 2>&1 || true
podman rm -f lsmdb-probe >/dev/null 2>&1 || true

check "replica path is auto-derived per file (no hand-written path)" "yes" \
	"$(grep -q 'path=bydir/delta.sqlite' <<<"$dirlog" && echo yes || echo no)"
check "a tenant db created AFTER startup is picked up with no restart" "yes" \
	"$(grep -q 'added database to replication.*echo.sqlite' <<<"$dirlog" && echo yes || echo no)"

# Restore addressing changes in dir mode: the config no longer names db paths.
set +e
dirconf_err=$(podman run --rm --network "$NET" --user 0 \
	-v "$WORK/data:/data:Z" -v "$WORK/restore:/restore:Z" \
	-v "$WORK/probe.yml:/etc/litestream.yml:ro,Z" \
	"$LITESTREAM_IMAGE" restore -config /etc/litestream.yml \
	-o /restore/dir-byconfig.sqlite /data/tenants/echo.sqlite 2>&1)
set -e
check "restore -config DB_PATH does NOT resolve in dir mode" "yes" \
	"$(grep -q 'database not found in config' <<<"$dirconf_err" && echo yes || echo no)"

podman run --rm --network "$NET" --user 0 -v "$WORK/restore:/restore:Z" \
	-e LITESTREAM_ACCESS_KEY_ID="$AKID" -e LITESTREAM_SECRET_ACCESS_KEY="$SECRET" \
	"$LITESTREAM_IMAGE" restore -o /restore/dir-byurl.sqlite \
	"s3://$BUCKET/bydir/echo.sqlite?endpoint=http://$MINIO_CTR:9000&region=us-east-1&force-path-style=true"
check "restore by REPLICA URL works in dir mode" "echo" \
	"$(sqlite3 "$WORK/restore/dir-byurl.sqlite" 'SELECT DISTINCT tenant FROM writes;')"

log "16. CONSTRAINT: Litestream 0.5 writes bookkeeping tables into each tenant DB"
lstables=$(sqlite3 "$WORK/data/$OTHER_A.sqlite" \
	"SELECT group_concat(name, ' ') FROM (SELECT name FROM sqlite_master \
	 WHERE type='table' AND name LIKE '\_litestream%' ESCAPE '\\' ORDER BY name);")
check "the tenant DB gains Litestream's own tables" "_litestream_lock _litestream_seq" "$lstables"
note "=> pkdump's JSON export enumerates user tables from sqlite_master and"
note "   excludes only 'sqlite_%', so these ride along."

log "VERDICT"
echo "checks passed: $pass   failed: $fail"
if [[ $fail -eq 0 ]]; then
	echo "PASS — one Litestream sidecar replicated ${#TENANTS[@]} databases and"
	echo "       restored tenant #2 to a chosen point in time independently."
	exit 0
fi
echo "FAIL — see the failures above and $WORK/litestream.log"
exit 1
