-- User-curated printings — the 'Missing Variant' escape hatch
-- (decision pokedumpster-x7k). Used when a copy in hand doesn't match
-- any catalog variant (misprints, undocumented promos, …) and the user
-- wants to log it now while the data model gets updated later.
--
-- printing_id is generated by the repository layer as
--   '{card_id}-user-{N}'
-- where N is the next per-card sequence. card_id is an app-layer FK to
-- shared.cards; variant references shared.variants (typically
-- 'missing_variant', seeded by shared migration V8).
--
-- description carries the free-text variant detail per row (e.g.
-- "no set stamp misprint"). collection rows reference printing_id and
-- carry their own per-copy condition / notes / etc.

CREATE TABLE user_printings (
    printing_id  TEXT PRIMARY KEY,
    card_id      TEXT NOT NULL,
    variant      TEXT NOT NULL DEFAULT 'missing_variant',
    description  TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_user_printings_card ON user_printings(card_id);
